#!/bin/bash

display_usage() { 
  echo "Open the Shopify admin editor for the development theme." >/dev/tty
	echo -e "Usage:\n$0 -h | -d | [store]" >/dev/tty
	}
 
display_help() { 
  display_usage
	echo "Options:"
	#echo -e " -v \tVerbose mode."
	#echo -e " -d \tDry-run mode."
	echo -e " -d \tUse development environment defined in shopify.theme.toml"
	echo -e " -h \tPrint this help message."
	echo ""
	}

#verbose='false'
hflag='false'
dflag='false'

while getopts 'dh' flag; do
  case "${flag}" in
    #v) verbose='true' ;;
    h) hflag='true' ;;
    d) dflag='true' ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

if [ "$hflag" == "true" ]; then
    display_help
    exit 0
fi

# Count positional arguments left
let "posArgCount = $# + 1 - $OPTIND" 1

storeUrl=""

if [ "$posArgCount" -gt 1 ]; then
    echo -e "Unexpected arguments ${@:$OPTIND:1}': ${@:$OPTIND+1}\n" >&2
    display_usage
    echo ""
    exit 1
elif [ "$posArgCount" -gt 0 ]; then
    storeUrl=${@:$OPTIND:1}
fi 

if [ "$dflag" == "true" ]; then
  shopify theme open --editor -d -e development
elif [ -z "${storeUrl}" ]; then
  shopify theme open --editor -d
else
  shopify theme open --editor -d -s "${storeUrl}"
fi
